# main.py
import json
from datetime import datetime
from expense import Expense
from tracker import ExpenseTracker
from report import ReportGenerator
from utils import safe_float

tracker = ExpenseTracker()
reporter = ReportGenerator()

def menu():
    print("\n==== Smart Expense Tracker ====")
    print("1. Add Expense")
    print("2. View All Expenses")
    print("3. Search Expense")
    print("4. Filter By Category")
    print("5. Filter By Date Range")
    print("6. Generate Monthly Excel Report")
    print("7. Generate Spending Trend Plot")
    print("8. Generate Category-wise Pie Chart")
    print("9. Generate Monthly Bar Chart")
    print("10. Generate Top 10 Highest Expenses Chart")
    print("11. Predict Next Month Spending")
    print("12. Generate Full PDF Report")
    print("13. Edit Project Info (project_info.json)")
    print("14. Exit")

def save_project_info_interactive():
    """
    Interactive prompt to create/update project_info.json.
    Team members can be added one-by-one.
    """
    info = {}
    info['project_title'] = input("Project title (default Smart Expense Tracker): ").strip() or "Smart Expense Tracker"
    info['project_name'] = input("Project name (optional): ").strip() or info['project_title']
    info['course'] = input("Course (optional): ").strip()
    info['institute'] = input("Institute (optional): ").strip()
    info['supervisor'] = input("Supervisor (optional): ").strip()
    info['semester'] = input("Semester (optional): ").strip()
    info['generated_by'] = input("Generated by (optional): ").strip() or "Smart Expense Tracker System"

    # team members
    team = []
    print("\nAdd team members (leave name blank to finish):")
    while True:
        name = input("Member name: ").strip()
        if not name:
            break
        role = input("Role (optional): ").strip() or "Member"
        team.append({"name": name, "role": role})
    info['team'] = team

    # Save file
    try:
        with open("project_info.json", "w", encoding="utf-8") as f:
            json.dump(info, f, indent=2, ensure_ascii=False)
        print("project_info.json saved successfully.")
    except Exception as e:
        print("Failed to save project_info.json:", e)

def read_and_print_df(df):
    """
    Nicely print pandas DataFrame (handles empty)
    """
    try:
        if df is None:
            print("No data.")
            return
        # If it's a DataFrame-like
        print(df.to_string(index=False))
    except Exception:
        # Fallback simple print
        print(df)

# Main loop
while True:
    menu()
    choice = input("Choose: ").strip()

    if choice == "1":
        try:
            date_str = input("Date (YYYY-MM-DD): ").strip()
            date = datetime.strptime(date_str, "%Y-%m-%d")
            category = input("Category: ").strip()
            amount = safe_float(input("Amount: ").strip())
            desc = input("Description: ").strip()

            exp = Expense(date, category, amount, desc)
            tracker.add_expense(exp)
            print("Expense added.")
        except Exception as e:
            print("Error adding expense:", e)

    elif choice == "2":
        try:
            df = tracker.read_expenses()
            read_and_print_df(df)
        except Exception as e:
            print("Error reading expenses:", e)

    elif choice == "3":
        text = input("Search text: ").strip()
        try:
            df = tracker.search(text)
            read_and_print_df(df)
        except Exception as e:
            print("Search error:", e)

    elif choice == "4":
        cat = input("Category: ").strip()
        try:
            df = tracker.filter_category(cat)
            read_and_print_df(df)
        except Exception as e:
            print("Filter error:", e)

    elif choice == "5":
        start = input("Start date (YYYY-MM-DD): ").strip()
        end = input("End date (YYYY-MM-DD): ").strip()
        try:
            df = tracker.filter_date(start, end)
            read_and_print_df(df)
        except Exception as e:
            print("Date filter error:", e)

    elif choice == "6":
        try:
            path = reporter.export_excel()
            if path:
                print("Excel generated:", path)
            else:
                print("No Excel file generated.")
        except Exception as e:
            print("Excel export error:", e)

    elif choice == "7":
        try:
            path = reporter.plot_trend()
            if path:
                print("Spending Trend Chart saved:", path)
            else:
                print("No plot generated.")
        except Exception as e:
            print("Plot error:", e)

    elif choice == "8":
        try:
            path = reporter.plot_category_pie()
            if path:
                print("Category Pie Chart saved:", path)
            else:
                print("No pie chart generated.")
        except Exception as e:
            print("Pie chart error:", e)

    elif choice == "9":
        try:
            path = reporter.plot_monthly_bar()
            if path:
                print("Monthly Bar Chart saved:", path)
            else:
                print("No bar chart generated.")
        except Exception as e:
            print("Bar chart error:", e)

    elif choice == "10":
        try:
            path = reporter.plot_top_expenses()
            if path:
                print("Top 10 Expenses Chart saved:", path)
            else:
                print("No top-10 chart generated.")
        except Exception as e:
            print("Top 10 chart error:", e)

    elif choice == "11":
        try:
            prediction = reporter.predict_next_month()
            if prediction is None:
                print("Unable to predict. Add more data (needs ≥2 months).")
            else:
                print(f"Predicted Next Month Spending: ₹{prediction}")
        except Exception as e:
            print("Prediction error:", e)

    elif choice == "12":
        try:
            path = reporter.generate_pdf_report()
            if path:
                print("Full PDF Report saved:", path)
            else:
                print("No PDF generated.")
        except Exception as e:
            print("PDF generation error:", e)

    elif choice == "13":
        save_project_info_interactive()

    elif choice == "14":
        print("Goodbye!")
        break

    else:
        print("Invalid option. Please choose again.")
# main.py
import json
from datetime import datetime
from expense import Expense
from tracker import ExpenseTracker
from report import ReportGenerator
from utils import safe_float

tracker = ExpenseTracker()
reporter = ReportGenerator()

def menu():
    print("\n==== Smart Expense Tracker ====")
    print("1. Add Expense")
    print("2. View All Expenses")
    print("3. Search Expense")
    print("4. Filter By Category")
    print("5. Filter By Date Range")
    print("6. Generate Monthly Excel Report")
    print("7. Generate Spending Trend Plot")
    print("8. Generate Category-wise Pie Chart")
    print("9. Generate Monthly Bar Chart")
    print("10. Generate Top 10 Highest Expenses Chart")
    print("11. Predict Next Month Spending")
    print("12. Generate Full PDF Report")
    print("13. Edit Project Info (project_info.json)")
    print("14. Exit")

def save_project_info_interactive():
    """
    Interactive prompt to create/update project_info.json.
    Team members can be added one-by-one.
    """
    info = {}
    info['project_title'] = input("Project title (default Smart Expense Tracker): ").strip() or "Smart Expense Tracker"
    info['project_name'] = input("Project name (optional): ").strip() or info['project_title']
    info['course'] = input("Course (optional): ").strip()
    info['institute'] = input("Institute (optional): ").strip()
    info['supervisor'] = input("Supervisor (optional): ").strip()
    info['semester'] = input("Semester (optional): ").strip()
    info['generated_by'] = input("Generated by (optional): ").strip() or "Smart Expense Tracker System"

    # team members
    team = []
    print("\nAdd team members (leave name blank to finish):")
    while True:
        name = input("Member name: ").strip()
        if not name:
            break
        role = input("Role (optional): ").strip() or "Member"
        team.append({"name": name, "role": role})
    info['team'] = team

    # Save file
    try:
        with open("project_info.json", "w", encoding="utf-8") as f:
            json.dump(info, f, indent=2, ensure_ascii=False)
        print("project_info.json saved successfully.")
    except Exception as e:
        print("Failed to save project_info.json:", e)

def read_and_print_df(df):
    """
    Nicely print pandas DataFrame (handles empty)
    """
    try:
        if df is None:
            print("No data.")
            return
        # If it's a DataFrame-like
        print(df.to_string(index=False))
    except Exception:
        # Fallback simple print
        print(df)

# Main loop
while True:
    menu()
    choice = input("Choose: ").strip()

    if choice == "1":
        try:
            date_str = input("Date (YYYY-MM-DD): ").strip()
            date = datetime.strptime(date_str, "%Y-%m-%d")
            category = input("Category: ").strip()
            amount = safe_float(input("Amount: ").strip())
            desc = input("Description: ").strip()

            exp = Expense(date, category, amount, desc)
            tracker.add_expense(exp)
            print("Expense added.")
        except Exception as e:
            print("Error adding expense:", e)

    elif choice == "2":
        try:
            df = tracker.read_expenses()
            read_and_print_df(df)
        except Exception as e:
            print("Error reading expenses:", e)

    elif choice == "3":
        text = input("Search text: ").strip()
        try:
            df = tracker.search(text)
            read_and_print_df(df)
        except Exception as e:
            print("Search error:", e)

    elif choice == "4":
        cat = input("Category: ").strip()
        try:
            df = tracker.filter_category(cat)
            read_and_print_df(df)
        except Exception as e:
            print("Filter error:", e)

    elif choice == "5":
        start = input("Start date (YYYY-MM-DD): ").strip()
        end = input("End date (YYYY-MM-DD): ").strip()
        try:
            df = tracker.filter_date(start, end)
            read_and_print_df(df)
        except Exception as e:
            print("Date filter error:", e)

    elif choice == "6":
        try:
            path = reporter.export_excel()
            if path: 
                print("Excel generated:", path)
            else:
                print("No Excel file generated.")
        except Exception as e:
            print("Excel export error:", e)

    elif choice == "7":
        try:
            path = reporter.plot_trend()
            if path:
                print("Spending Trend Chart saved:", path)
            else:
                print("No plot generated.")
        except Exception as e:
            print("Plot error:", e)

    elif choice == "8":
        try:
            path = reporter.plot_category_pie()
            if path:
                print("Category Pie Chart saved:", path)
            else:
                print("No pie chart generated.")
        except Exception as e:
            print("Pie chart error:", e)

    elif choice == "9":
        try:
            path = reporter.plot_monthly_bar()
            if path:
                print("Monthly Bar Chart saved:", path)
            else:
                print("No bar chart generated.")
        except Exception as e:
            print("Bar chart error:", e)

    elif choice == "10":
        try:
            path = reporter.plot_top_expenses()
            if path:
                print("Top 10 Expenses Chart saved:", path)
            else:
                print("No top-10 chart generated.")
        except Exception as e:
            print("Top 10 chart error:", e)

    elif choice == "11":
        try:
            prediction = reporter.predict_next_month()
            if prediction is None:
                print("Unable to predict. Add more data (needs ≥2 months).")
            else:
                print(f"Predicted Next Month Spending: ₹{prediction}")
        except Exception as e:
            print("Prediction error:", e)

    elif choice == "12":
        try:
            path = reporter.generate_pdf_report()
            if path:
                print("Full PDF Report saved:", path)
            else:
                print("No PDF generated.")
        except Exception as e:
            print("PDF generation error:", e)

    elif choice == "13":
        save_project_info_interactive()

    elif choice == "14":
        print("Goodbye!")
        break

    else:
        print("Invalid option. Please choose again.")
